#!/bin/sh 
#maps reads to G. cryophila 
#unmapped reads from M. rubrum assembeled 
for sample in $(cat ~/data/Mrubrum/samples)
do

    bbmap.sh in=~/data/Mrubrum/${sample}.fq.gz \
    unpigz=t pigz=t slow k=12 \
    ref=~/data/Mrubrum/Gcryo.fasta \
    outm=~/data/Gcryo/${sample}_Gcryo.fq \
    outu=~/data/Mrubrum/${sample}_Mr.fq \
    printunmappedcount=t covk=1 nfilter=10 interleaved=f maxindel=20 threads=24 minid=0.90 ambiguous=all maxsites2=20000 physcov=t \

done

#assemble M rubrum
spades.py --rna -t 16 \
--s1 ~/data/Mrubrum/SRR10126743_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126744_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126745_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126746_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126747_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126748_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126749_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126750_Mr.fq \
--s1 ~/data/Mrubrum/SRR10126751_Mr.fq \
-o ~/data/genome/Mrubrum/assembely

#Transdecoder to predict reading frames
TransDecoder.LongOrfs --genetic_code Mesodinium -t ~/data/Mrubrum/assembely/transcripts.fasta
TransDecoder.Predict --genetic_code Mesodinium -t ~/data/Mrubrum/assembely/transcripts.fasta

