#!/bin/sh 
#uses bbmap to map reads to T. amphioxeia nulcleotide transcriptome
#unmapped reads are temperate M. rubrum  

for sample in $(cat /home/cpaight/cpaightNAS/cpaight/data/temperateMrubrum/mtempRubrum/Mr2A1/samples)
do

    echo "On sample: $sample"

    bbmap.sh in=~/temperateMrubrum/mtempRubrum/Mr2A1/${sample}_R1_001.fastq.gz  \
    in2=~/data/temperateMrubrum/mtempRubrum/Mr2A1/${sample}_R2_001.fastq.gz  \
    unpigz=t pigz=t slow k=12 pairedonly=t \
    ref=~/data/temperateMrubrum/cryptophyte/transcripts.fasta \
    outm=~/data/temperateMrubrum/mtempRubrum/Mr2A1/mapped/${sample}.fq \
    outu=~/data/temperateMrubrum/mtempRubrum/Mr2A1/unmapped/${sample}.fq \
    printunmappedcount=t \

done

# first temperate M. rubrum assembly with spades
spades.py --rna -t 32 \
--pe1-1 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L001_R1_001.fastq.gz \
--pe2-1 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L002_R1_001.fastq.gz \
--pe3-1 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L003_R1_001.fastq.gz \
--pe4-1 ~/cpaight/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L004_R1_001.fastq.gz \
--pe5-1 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L001_R1_001.fastq.gz \
--pe6-1 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L002_R1_001.fastq.gz \
--pe7-1 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L003_R1_001.fastq.gz \
--pe8-1 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L004_R1_001.fastq.gz \
--pe1-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L001_R2_001.fastq.gz \
--pe2-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L002_R2_001.fastq.gz \
--pe3-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L003_R2_001.fastq.gz \
--pe4-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-5_S4_L004_R2_001.fastq.gz \
--pe5-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L001_R2_001.fastq.gz \
--pe6-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L002_R2_001.fastq.gz \
--pe7-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L003_R2_001.fastq.gz \
--pe8-2 ~/data/temperateMrubrum/mtempRubrum/Mr2A1/128930-6_S5_L004_R2_001.fastq.gz \
-o ~/data/temperateMrubrum/mtempRubrum/Mr2A1/all/

#Transdecoder to predict reading frames
TransDecoder.LongOrfs --genetic_code Mesodinium -t ~/data/temperateMrubrum/mtempRubrum/Mr2A1/all/transcripts.fasta
TransDecoder.Predict --genetic_code Mesodinium -t ~/data/temperateMrubrum/mtempRubrum/Mr2A1/all/transcripts.fasta
