#!/bin/sh 
#uses bbmap to map reads to T. amphioxeia nulcleotide transcriptome
#unmapped reads are temperate M. rubrum  

for sample in $(cat /home/cpaight/cpaightNAS/cpaight/data/temperateMrubrum/mtempRubrum/Mr2A1/samples)
do

    echo "On sample: $sample"

    bbmap.sh in=~/temperateMrubrum/mtempRubrum/Mr2A1/${sample}_R1_001.fastq.gz  \
    in2=~/data/temperateMrubrum/mtempRubrum/Mr2A1/${sample}_R2_001.fastq.gz  \
    unpigz=t pigz=t slow k=12 pairedonly=t \
    ref=~/data/temperateMrubrum/cryptophyte/transcripts.fasta \
    outm=~/data/temperateMrubrum/mtempRubrum/Mr2A1/mapped/${sample}.fq \
    outu=~/data/temperateMrubrum/mtempRubrum/Mr2A1/unmapped/${sample}.fq \
    printunmappedcount=t \

done

# first M. pulex assembly with spades
spades.py --rna -t 16 \
--s1 ~/data/Mpulex/unmapped/MP3_S95_L002.fq \
--s2 ~/data/Mpulex/unmapped/MP4_S96_L002.fq \
--s3 ~/data/Mpulex/unmapped/MP5_S97_L002.fq \
--s4 ~/data/Mpulex/unmapped/MP6_S98_L002.fq \
--s5 ~/data/Mpulex/unmapped/MP7_S99_L002.fq \
-o ~/data/Mpulex/unmapped/assem

#Transdecoder to predict reading frames
TransDecoder.LongOrfs --genetic_code Mesodinium -t ~/data/Mpulex/unmapped/assem/transcripts.fasta
TransDecoder.Predict --genetic_code Mesodinium -t ~/data/Mpulex/unmapped/assem/transcripts.fasta
