#!/bin/sh 
#uses bbmap to map reads to S. major nulcleotide transcriptome
#unmapped reads are M. Mchameleon   

for sample in $(cat ~/data/Mchameleon/jgi/Mcsamples)
do

    bbmap.sh in=~/data/Mchameleon/jgi/${sample}-RNA.fastq.gz \
    unpigz=t pigz=t slow k=12 \
    ref=~/data/Mchameleon/jgi/smajor/Stomajnscriptome/transcripts.fasta \
    outm=~/data/Mchameleon/jgi/mapping/jgiSm8/${sample}_sm.fq \
    outu=~/data/Mchameleon/jgi/mapping/jgiMC8/${sample}_MC.fq \
    printunmappedcount=t covk=1 nfilter=10 interleaved=f maxindel=20 threads=24 minid=0.90 ambiguous=all maxsites2=20000 physcov=t \

done


# first M. chameleon assembly with spades
spades.py --rna -t 16 \
--s1 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.ACCTCTGT-ACCTCTGT.filter_MC.fq \
--s2 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.ATGCCTGT-ATGCCTGT.filter_MC.fq \
--s3 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.ATGGTCCA-ATGGTCCA.filter_MC.fq \
--s4 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.CACGTTGT-CACGTTGT.filter_MC.fq \
--s5 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.CACTGACA-CACTGACA.filter_MC.fq \
--s6 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.CAGAGTGT-CAGAGTGT.filter_MC.fq \
--s7 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.CATACCAC-CATACCAC.filter_MC.fq \
--s8 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.CCAAGCAA-CCAAGCAA.filter_MC.fq \
--s9 ~/data/Mchameleon/jgi/mapping/jgiMC8/52663.3.414974.CGAACTGT-CGAACTGT.filter_MC.fq \
-o ~/data/Mchameleon/jgi/mapping/jgiMC8/

#Transdecoder to predict reading frames
TransDecoder.LongOrfs --genetic_code Mesodinium -t ~/data/Mchameleon/jgi/mapping/jgiMC8/transcripts.fasta
TransDecoder.Predict --genetic_code Mesodinium -t ~/data/Mchameleon/jgi/mapping/jgiMC8/transcripts.fasta
