#!/bin/sh 
#uses bbmap to map reads to S. major nulcleotide transcriptome
#unmapped reads are M. pulex  
for sample in $(cat ~/data/Mpulex/raw_data/Mpsamples)
do

    bbmap.sh in=~/data/Mpulex/raw_data/${sample}_R1_001.fastq.gz  \
    in2=~/data/Mpulex/raw_data/${sample}_R2_001.fastq.gz   \
    unpigz=t pigz=t slow k=12 pairedonly=t \
    ref=~/data/Mchameleon/raw_data/mapping/algaefianl/AlgaeDeco/algaeDecoCDS/SMnulc.fasta \
    outm=~/data/Mpulex/SM/${sample}.fq \
    outu=~/data/Mpulex/unmapped/${sample}.fq \
    printunmappedcount=t covk=1 nfilter=10 interleaved=f maxindel=20 threads=24 minid=0.90 ambiguous=all maxsites2=20000 physcov=t \

done

# first M. pulex assembly with spades
spades.py --rna -t 16 \
--s1 ~/data/Mpulex/unmapped/MP3_S95_L002.fq \
--s2 ~/data/Mpulex/unmapped/MP4_S96_L002.fq \
--s3 ~/data/Mpulex/unmapped/MP5_S97_L002.fq \
--s4 ~/data/Mpulex/unmapped/MP6_S98_L002.fq \
--s5 ~/data/Mpulex/unmapped/MP7_S99_L002.fq \
-o ~/data/Mpulex/unmapped/assem

#Transdecoder to predict reading frames
TransDecoder.LongOrfs --genetic_code Mesodinium -t ~/data/Mpulex/unmapped/assem/transcripts.fasta
TransDecoder.Predict --genetic_code Mesodinium -t ~/data/Mpulex/unmapped/assem/transcripts.fasta
